version: '3.5'
services:
# 默认创建test数据库和person表
  mybatis:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
    networks:
      network:
        ipv4_address: 172.16.0.2

networks:
  network:
    name: docker-net
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.0.0/16